# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ed9a87be19caf10a94a9c0a9241a9621578d57e75fe9bd03811241ff546cae3dd98453a37758c31293ebd5a54b5001e04de7cd0391480139d3620da18a09f0e

test:
  secret_key_base: 04321b087a69550dcd301178c09e58301ec51813a42b9fd64e95a8b27cb766c27e71c2b6b6c811d02abe7ed38f59ce55870cb92a53671218113eda4203e114ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
